services:
  - type: web
    name: my-laravel-app
    env: php
    plan: free
    buildCommand: "composer install && npm install && npm run dev && php artisan key:generate"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        fromDatabase: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
